artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1f0KyaqPa3UeDSRN1TR_RnVL9WCTwIb10/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/updated_base_model.h5


training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5

mlflow_config:
  mlflow_uri: https://dagshub.com/rdx7211/End-to-End-Chest-cancer-classification-project-.mlflow  
